config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get '/rghost-39', :to => redirect('/redirectpage.html')
  
  
  get 'home', :to => redirect('/')
  
  resources :applications
  get "/applications/new/:ptid" => "applications#new", :as => :new_application_with_parameter

  resources :patient_applications

  resources :pharm_manufacturers

  resources :medications_rx_norms
  
  get "/inventories/pap", :to => 'inventories#index'
  get "/inventories/general", :to => 'inventories#general'
  get "/inventories/new" => "inventories#new", :as => :new_inventory_with_parameter
  resources :inventories

  resources :dispensed_meds
  get "/dispensed_meds/new/:ptid" => "dispensed_meds#new", :as => :new_dispensed_med_with_parameter

  resources :providers

  resources :prescriptions

  resources :patients
  
  resources :activities

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  has_many :prescription_providers
  has_many :providers, :through => :prescription_providers
  
  has_many :prescription_medications_rx_norms
  has_many :medications_rx_norms, :through => :prescription_medications_rx_norms
  
  has_many :prescription_patients
  has_many :patients, :through => :prescription_patients
  
  validates_uniqueness_of :rxid
  validates :rxid, :numericality => { :greater_than_or_equal_to => 1 }
  validates_presence_of :dose
  validates_presence_of :frequencytaken
  validates_presence_of :routetaken
  validates_presence_of :dategiven
  validates_presence_of :medicationsrxnormndc
  validates_presence_of :providersdrid
  validates :providersdrid, :numericality => { :greater_than_or_equal_to => 1 }
  validates_presence_of :patientsptid
  validates :patientsptid, :numericality => { :greater_than_or_equal_to => 1 }
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @prescriptions = Prescription.all
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:rxid, :dose, :frequencytaken, :routetaken, :dategiven, :medicationsrxnormndc, :providersdrid, :patientsptid)
    end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@prescription) do |f| %>
      <% if @prescription.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>
    
          <ul>
          <% @prescription.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= f.label "Rx ID" %><br>
        <%= f.number_field :rxid, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Dose" %><br>
        <%= f.text_field :dose, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Frequency Taken" %><br>
        <%= f.text_field :frequencytaken, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Route Taken" %><br>
        <%= f.text_field :routetaken, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Date Given" %><br>
        <%= f.date_select :dategiven, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "RxNorm NDC" %><br>
        <%= f.text_field :medicationsrxnormndc, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Provider ID" %><br>
        <%= f.number_field :providersdrid, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Patient ID" %><br>
        <%= f.number_field :patientsptid, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit "Create Prescription", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/prescriptions/edit.html.erb
<% provide(:title, "Edit Prescription") %>
<h1>Editing Prescription</h1>

<%= render 'form' %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prescriptions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Rxid</th>
      <th>Dose</th>
      <th>Frequency Taken</th>
      <th>Route Taken</th>
      <th>Date Given</th>
      <th>Medication RxNorm NDC</th>
      <th>Provider ID</th>
      <th>Patient ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td><%= prescription.rxid %></td>
        <td><%= prescription.dose %></td>
        <td><%= prescription.frequencytaken %></td>
        <td><%= prescription.routetaken %></td>
        <td><%= prescription.dategiven %></td>
        <td><%= prescription.medicationsrxnormndc %></td>
        <td><%= prescription.providersdrid %></td>
        <td><%= prescription.patientsptid %></td>
        <td><%= link_to 'Show', prescription %></td>
        <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
        <td><%= link_to 'Destroy', prescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New Prescription</h1>

<%= render 'form' %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rxid:</strong>
  <%= @prescription.rxid %>
</p>

<p>
  <strong>Dose:</strong>
  <%= @prescription.dose %>
</p>

<p>
  <strong>Frequencytaken:</strong>
  <%= @prescription.frequencytaken %>
</p>

<p>
  <strong>Routetaken:</strong>
  <%= @prescription.routetaken %>
</p>

<p>
  <strong>Dategiven:</strong>
  <%= @prescription.dategiven %>
</p>

<p>
  <strong>Medicationsrxnormndc:</strong>
  <%= @prescription.medicationsrxnormndc %>
</p>

<p>
  <strong>Providersdrid:</strong>
  <%= @prescription.providersdrid %>
</p>

<p>
  <strong>Patientsptid:</strong>
  <%= @prescription.patientsptid %>
</p>

<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>