config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get '/rghost-39', :to => redirect('/redirectpage.html')
  
  
  get 'home', :to => redirect('/')
  
  resources :applications
  get "/applications/new/:ptid" => "applications#new", :as => :new_application_with_parameter

  resources :patient_applications

  resources :pharm_manufacturers

  resources :medications_rx_norms
  
  get "/inventories/pap", :to => 'inventories#index'
  get "/inventories/general", :to => 'inventories#general'
  get "/inventories/new" => "inventories#new", :as => :new_inventory_with_parameter
  resources :inventories

  resources :dispensed_meds
  get "/dispensed_meds/new/:ptid" => "dispensed_meds#new", :as => :new_dispensed_med_with_parameter

  resources :providers

  resources :prescriptions

  resources :patients
  
  resources :activities

end

app/models/application.rb
class Application < ActiveRecord::Base
  include PublicActivity::Model
  tracked
  
  def firstname
    Patient.where(ptid: patientsptid).pluck(:firstname)
  end
  
  def lastname
    Patient.where(ptid: patientsptid).pluck(:lastname)
  end
  
  def manufacturer
    puts PharmManufacturer.where(manufacturer: pharmmanufacturersphid).pluck(:manufacturer)
    
    PharmManufacturer.where(phid: pharmmanufacturersphid).pluck(:manufacturer)
  end
  
  def medname
    puts MedicationsRxNorm.where(ndc: medicationsrxnormndc).pluck(:medname)
    
    MedicationsRxNorm.where(ndc: medicationsrxnormndc).pluck(:medname)
  end
  
  has_many :application_medications_rx_norms
  has_many :medications_rx_norms, :through => :application_medications_rx_norms
  
  has_many :application_patients
  has_many :patients, :through => :application_patients
  
  has_many :application_pharm_manufacturers
  has_many :pharm_manufacturers, :through => :application_pharm_manufacturers
  
  validates :patientsptid, :numericality => { :greater_than_or_equal_to => 1 }
  validates :pharmmanufacturersphid, :numericality => { :greater_than_or_equal_to => 1 }
  validates_presence_of :appstatus
  validates_presence_of :dateinit
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def greeting
    render text: "Charles is a thespian"
  end
  
  def redirect_with_delay(url, delay = 0)
    @redirect_url, @redirect_delay = url, delay
    render
  end
  
  helper_method :reorder
  
  def reorder
    
    
    Inventory.all.each do |inventory|
      reorderdate = Date.new(Date.today.year, inventory.datetoreorder.month, inventory.datetoreorder.day)
      reorderdate += 1.year if Date.today >= reorderdate
      if((reorderdate - Date.today).to_i <= 90)
        if()
          inventory.create_activity key: 'inventory.reorder'
        end
      end
    end
    puts "THIS METHOD RAN!"
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :load_activities, only: [:index, :show, :new, :edit]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
    
    @application.patientsptid = params[:ptid]
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:patientsptid, :pharmmanufacturersphid, :medicationsrxnormndc, :appstatus, :dateinit)
    end
    
    def load_activities
      @activities = PublicActivity::Activity.order('created_at DESC')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def full_title(page_title)
  base_title = "RxMAGIC"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
 end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@application) do |f| %>
      <% if @application.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>
    
          <ul>
          <% @application.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= f.label "Patient ID" %><br>
        <%= f.number_field :patientsptid, class: 'form-control', :readonly => true %>
      </div>
      <div>
        <label>Patient Name</label>
        <p><% @application.firstname.each do |firstname| %><%= firstname %> <% end %><% @application.lastname.each do |lastname| %><%= lastname %><% end %></p>
      </div>
      <div class="field">
        <%= f.label "Pharmaceutical Manufacturer ID" %><br>
        <%= collection_select(:application, :pharmmanufacturersphid, PharmManufacturer.all, :phid, :manufacturer) %>
      </div>
      <div class="field">
        <%= f.label "Medication RxNorm NDC" %><br>
        <%= collection_select(:application, :medicationsrxnormndc, MedicationsRxNorm.all, :ndc, :medname) %>
      <div class="field">
        <%= f.label "Application Status" %><br>
        <%= f.select :appstatus, options_for_select([['Holding', 'Holding'], ['Progress', 'Progress'], ['Pending', 'Pending'], ['Accepted', 'Accepted'], ['Received', 'Received']], @application.appstatus) %>
      </div>
      <div class="field">
        <%= f.label "Date Initiated" %><br>
        <%= f.date_select :dateinit, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit "Create Application", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/applications/edit.html.erb
<% provide(:title, "Edit Application") %>
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Applications</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Patient ID</th>
      <th>Pharmaceutical Manufacturer ID</th>
      <th>Medication RxNorm NDC</th>
      <th>App Status</th>
      <th>Date Initiated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.patientsptid %></td>
        <td><%= application.pharmmanufacturersphid %></td>
        <td><%= application.medicationsrxnormndc %></td>
        <td><%= application.appstatus %></td>
        <td><%= application.dateinit %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patients ID:</strong>
  <%= @application.patientsptid %>
</p>

<p>
  <strong>Patient Name:</strong>
  <% @application.firstname.each do |firstname| %><%= firstname %> <% end %><% @application.lastname.each do |lastname| %><%= lastname %><% end %>
</p>

<p>
  <strong>Pharmaceutical Manufacturer ID:</strong>
  <%= @application.pharmmanufacturersphid %>
</p>

<p>
  <strong>Pharmaceutical Manufacturer:</strong>
  <% @application.manufacturer.each do |manufacturer| %><%= manufacturer %> <% end %>
</p>

<p>
  <strong>Medication RxNorm NDC:</strong>
  <%= @application.medicationsrxnormndc %>
</p>

<p>
  <strong>Medicine Name:</strong>
  <% @application.medname.each do |medname| %><%= medname %> <% end %>
</p>

<p>
  <strong>Application Status:</strong>
  <%= @application.appstatus %>
</p>

<p>
  <strong>Date Initiated:</strong>
  <%= @application.dateinit %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>