config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  
  get '/rghost-39', :to => redirect('/redirectpage.html')
  
  
  get 'home', :to => redirect('/')
  
  resources :applications
  get "/applications/new/:ptid" => "applications#new", :as => :new_application_with_parameter

  resources :patient_applications

  resources :pharm_manufacturers

  resources :medications_rx_norms
  
  get "/inventories/pap", :to => 'inventories#index'
  get "/inventories/general", :to => 'inventories#general'
  get "/inventories/new" => "inventories#new", :as => :new_inventory_with_parameter
  resources :inventories

  resources :dispensed_meds
  get "/dispensed_meds/new/:ptid" => "dispensed_meds#new", :as => :new_dispensed_med_with_parameter

  resources :providers

  resources :prescriptions

  resources :patients
  
  resources :activities

end

app/models/pharm_manufacturer.rb
class PharmManufacturer < ActiveRecord::Base
  has_many :application_pharm_manufacturers
  has_many :applications, :through => :application_pharm_manufacturers

  has_many :medications_rx_norm_pharm_manufacturers
  has_many :medications_rx_norms, :through => :medications_rx_norm_pharm_manufacturers

  validates_uniqueness_of :phid
  validates :phid, :numericality => { :greater_than_or_equal_to => 1 }
  validates_presence_of :manufacturer
  validates_presence_of :minincome
  validates_presence_of :monthsreorder
end

app/controllers/pharm_manufacturers_controller.rb
class PharmManufacturersController < ApplicationController
  before_action :set_pharm_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /pharm_manufacturers
  # GET /pharm_manufacturers.json
  def index
    @pharm_manufacturers = PharmManufacturer.all
  end

  # GET /pharm_manufacturers/1
  # GET /pharm_manufacturers/1.json
  def show
  end

  # GET /pharm_manufacturers/new
  def new
    @pharm_manufacturer = PharmManufacturer.new
    @pharm_manufacturer.phid = PharmManufacturer.maximum(:phid).to_i.next
  end

  # GET /pharm_manufacturers/1/edit
  def edit
  end

  # POST /pharm_manufacturers
  # POST /pharm_manufacturers.json
  def create
    @pharm_manufacturer = PharmManufacturer.new(pharm_manufacturer_params)

    respond_to do |format|
      if @pharm_manufacturer.save
        format.html { redirect_to @pharm_manufacturer, notice: 'Pharm manufacturer was successfully created.' }
        format.json { render :show, status: :created, location: @pharm_manufacturer }
      else
        format.html { render :new }
        format.json { render json: @pharm_manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pharm_manufacturers/1
  # PATCH/PUT /pharm_manufacturers/1.json
  def update
    respond_to do |format|
      if @pharm_manufacturer.update(pharm_manufacturer_params)
        format.html { redirect_to @pharm_manufacturer, notice: 'Pharm manufacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @pharm_manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @pharm_manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharm_manufacturers/1
  # DELETE /pharm_manufacturers/1.json
  def destroy
    @pharm_manufacturer.destroy
    respond_to do |format|
      format.html { redirect_to pharm_manufacturers_url, notice: 'Pharm manufacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharm_manufacturer
      @pharm_manufacturer = PharmManufacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharm_manufacturer_params
      params.require(:pharm_manufacturer).permit(:phid, :manufacturer, :minincome, :monthsreorder)
    end
end

app/helpers/pharm_manufacturers_helper.rb
module PharmManufacturersHelper
end

app/views/pharm_manufacturers/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@pharm_manufacturer) do |f| %>
      <% if @pharm_manufacturer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pharm_manufacturer.errors.count, "error") %> prohibited this pharm_manufacturer from being saved:</h2>
    
          <ul>
          <% @pharm_manufacturer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= f.label "Pharmaceutical Manufacturer ID" %><br>
        <%= f.number_field :phid, class: 'form-control', :readonly => true %>
      </div>
      <div class="field">
        <%= f.label "Pharmaceutical Manufacturer" %><br>
        <%= f.text_field :manufacturer, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Minimum Income" %><br>
        <%= f.text_field :minincome, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Months Reorder" %><br>
        <%= f.text_field :monthsreorder, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit "Create Pharmaceutical Manufacturer", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pharm_manufacturers/edit.html.erb
<% provide(:title, "Pharmaceutical Manufacturer") %>
<h1>Editing Pharm Manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @pharm_manufacturer %> |
<%= link_to 'Back', pharm_manufacturers_path %>

app/views/pharm_manufacturers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pharm Manufacturers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Manufacturer ID</th>
      <th>Manufacturer</th>
      <th>Minimum Income</th>
      <th>Months Reorder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pharm_manufacturers.each do |pharm_manufacturer| %>
      <tr>
        <td><%= pharm_manufacturer.phid %></td>
        <td><%= pharm_manufacturer.manufacturer %></td>
        <td><%= pharm_manufacturer.minincome %></td>
        <td><%= pharm_manufacturer.monthsreorder %></td>
        <td><%= link_to 'Show', pharm_manufacturer %></td>
        <td><%= link_to 'Edit', edit_pharm_manufacturer_path(pharm_manufacturer) %></td>
        <td><%= link_to 'Destroy', pharm_manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pharm manufacturer', new_pharm_manufacturer_path %>

app/views/pharm_manufacturers/new.html.erb
<h1>New Pharmaceutical Manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', pharm_manufacturers_path %>

app/views/pharm_manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phid:</strong>
  <%= @pharm_manufacturer.phid %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @pharm_manufacturer.manufacturer %>
</p>

<p>
  <strong>Minincome:</strong>
  <%= @pharm_manufacturer.minincome %>
</p>

<p>
  <strong>Monthsreorder:</strong>
  <%= @pharm_manufacturer.monthsreorder %>
</p>

<%= link_to 'Edit', edit_pharm_manufacturer_path(@pharm_manufacturer) %> |
<%= link_to 'Back', pharm_manufacturers_path %>